"use client";
import {useState} from "react";
const initial=[
 {id:1,org:"启德教育",title:"2026全球留学趋势报告发布",source:"官方网站",date:"2026-07-10",url:"https://www.eic.org.cn/",summary:"以年度趋势数据建立行业权威，同时引导用户领取完整报告并进入顾问咨询。",confidence:"A",type:"行业报告"},
 {id:2,org:"新航道",title:"与海外院校新增合作项目",source:"官方网站",date:"2026-07-09",url:"https://www.xhd.cn/",summary:"合作资质被包装为申请资源与服务能力背书，可能服务于高端项目转化。",confidence:"A",type:"合作背书"},
 {id:3,org:"美世教育",title:"广州站新加坡名校申请私享会",source:"公开活动页",date:"2026-07-09",url:"https://www.mcedu.com/",summary:"以限额私享会触达高净值家庭，内容从录取结果转向规划诊断。",confidence:"B",type:"线下活动"},
 {id:4,org:"新东方前途出国",title:"高考后多路径升学方案",source:"公开新闻",date:"2026-07-08",url:"https://liuxue.xdf.cn/",summary:"通过高考节点焦虑切入，将留学申请包装为国内外双轨规划。",confidence:"A",type:"路径规划"}
];
export default function Review(){const [items,setItems]=useState(initial);const [selected,setSelected]=useState(initial[0]);const [filter,setFilter]=useState("待审核");function act(id:number){setItems(v=>v.filter(x=>x.id!==id));setSelected(items.find(x=>x.id!==id)||initial[0])}return <main className="subpage"><header className="subnav"><a className="brand" href="/"><span className="mark">见</span><div>竞见<small>竞品外宣情报工作台</small></div></a><nav><a href="/">工作台</a><a className="active" href="/review">审核箱</a><a href="/competitors">竞品洞察</a></nav><span className="queue-count">{items.length} 条待处理</span></header><section className="page-title"><div><span className="eyebrow">EVIDENCE REVIEW</span><h1>自动发现审核箱</h1><p>先看原始证据，再决定是否纳入竞品库。每条结论保留来源、时间与置信度。</p></div><div className="review-stats"><b>{items.length}</b><span>待审核</span><b>18</b><span>本周已入库</span><b>7</b><span>已排除</span></div></section><section className="review-layout"><aside className="review-list card"><div className="review-tabs">{["待审核","已入库","已忽略"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{items.length?items.map(x=><button className={`review-item ${selected.id===x.id?"selected":""}`} onClick={()=>setSelected(x)} key={x.id}><div><span className="source-dot official">{x.source.slice(0,2)}</span><small>{x.date}</small></div><b>{x.org}</b><p>{x.title}</p><span className="mini-tag">{x.type}</span></button>):<div className="empty">当前队列已处理完毕</div>}</aside><article className="evidence card"><div className="evidence-head"><div><span className="mini-tag">来源可信度 {selected.confidence}</span><h2>{selected.title}</h2><p>{selected.org} · {selected.source} · {selected.date}</p></div><a className="primary source-button" href={selected.url} target="_blank" rel="noreferrer">打开原始链接 ↗</a></div><div className="evidence-preview"><div className="browser-bar"><i></i><i></i><i></i><span>{selected.url}</span></div><div className="source-sheet"><span className="eyebrow">ORIGINAL SOURCE PREVIEW</span><h3>{selected.title}</h3><p>该区域用于展示网页快照、上传截图或PDF首屏。正式监测将保存抓取时间与原始页面地址，防止后续内容变化后无法溯源。</p><div className="snapshot"><b>{selected.org}</b><span>{selected.type}</span></div></div></div><div className="evidence-analysis"><section><small>内容摘要</small><p>{selected.summary}</p></section><section><small>系统识别</small><div className="chips"><span>目标客群：留学家庭</span><span>营销目的：获客与权威</span><span>CTA：领取资料/预约</span></div></section><section><small>审核备注</small><textarea placeholder="补充人工判断、需要验证的信息或使用限制…"/></section></div><div className="review-actions"><button className="reject" onClick={()=>act(selected.id)}>忽略此线索</button><button className="ghost">标记待验证</button><button className="primary" onClick={()=>act(selected.id)}>确认入库并分析</button></div></article></section></main>}
