"use client";
import {useState} from "react";
const competitors=[
 {name:"启德教育",kind:"全国头部",tone:"blue",signals:34,trend:"升温",business:["多国留学申请","国际教育规划","境外服务","行业研究"],style:["数据权威","政策解读","全国联动","专业理性"],moves:["发布全球留学趋势报告","强化官方合作资质","布局境外服务内容"],strategy:"以报告和政策内容建立行业话语权，再通过资料领取将公域流量沉淀到顾问咨询。",audience:"重视机构规模与服务确定性的中产家庭",cta:"报告领取 → 顾问评估 → 全链路方案",opportunity:"用更具体的过程型案例与本地服务透明度形成差异。"},
 {name:"美世教育",kind:"高端精品",tone:"purple",signals:27,trend:"升温",business:["高端美本","英美本科规划","背景提升","高净值活动"],style:["名校结果","稀缺限额","专家背书","精致克制"],moves:["广州私享会","前招生官内容系列","新加坡方向升温"],strategy:"以高端录取与专家身份筛选客群，通过限额活动制造稀缺感并完成高客单转化。",audience:"高净值、目标名校、接受长周期规划的家庭",cta:"专家内容 → 私享会 → 一对一规划",opportunity:"在高端叙事之外强化交付透明与真实过程证据。"},
 {name:"新东方前途出国",kind:"全国头部",tone:"orange",signals:41,trend:"稳定",business:["全阶段留学","语言培训联动","中外合办","就业与境外服务"],style:["规模背书","节点营销","路径教育","内容高频"],moves:["高考后多路径专题","总部内容全国分发","申请季直播矩阵"],strategy:"围绕升学关键节点进行搜索占位，用多路径内容扩大目标客群，并承接至综合规划产品。",audience:"从普高到国际学校的广泛家庭",cta:"节点焦虑 → 路径测评 → 综合方案",opportunity:"避开大而全竞争，聚焦广州本地与细分客群决策场景。"},
 {name:"新航道",kind:"语培+留学",tone:"green",signals:22,trend:"稳定",business:["语言培训","留学申请","国际课程","院校合作"],style:["资质密集","课程专业","师资IP","合作背书"],moves:["课程体系升级","新增院校合作","语言与申请联动"],strategy:"通过教学体系和官方合作降低信任成本，将语培客户自然延伸到留学申请。",audience:"需要语言成绩与申请一体化服务的学生",cta:"课程内容 → 测评试听 → 留学规划",opportunity:"强调规划与申请的独立专业度，避免被语培入口锁定。"},
 {name:"浑朴",kind:"高端美本工作室",tone:"purple",signals:9,trend:"稳定",business:["高端美本","Activity规划","选校文书","长期成长"],style:["克制稀缺","学生个性","录取结果","成长叙事"],moves:["限额服务","Top30结果","浑朴Activity"],strategy:"用限额和个性化活动方法论制造精品稀缺感。",audience:"重视个性化与Top30结果的美本家庭",cta:"理念 → 案例 → 深度咨询",opportunity:"借鉴限额与方法论包装，并强化透明交付。"},
 {name:"引知 InGenius Prep",kind:"全球高端升学",tone:"blue",signals:14,trend:"升温",business:["前招生官","未来领袖","科研领导力","多阶段申请"],style:["专家权威","量化结果","全球团队","体系交付"],moves:["未来领袖计划","前招生官直播","Genie进度平台"],strategy:"以前招生官和双导师制度建立壁垒，将服务前移到初中。",audience:"目标顶尖美本且接受多年规划的家庭",cta:"专家直播 → 免费咨询 → 长周期产品",opportunity:"研究服务可视化、进度管理与长线产品。"},
 {name:"棒呆",kind:"跨区域高端留学",tone:"green",signals:12,trend:"升温",business:["美英加本科","美初美高","夏校提升","学习工具"],style:["结果证明","顾问IP","专业长文","高端资源"],moves:["2026录取","顾问履历","申请季内容"],strategy:"以录取结果和顾问IP双重背书塑造规模化精品机构。",audience:"目标美英名校与低龄申请家庭",cta:"结果内容 → 评估 → 高端申请",opportunity:"用过程型案例对冲结果叙事。"},
 {name:"威学一百",kind:"大湾区综合国际教育",tone:"orange",signals:10,trend:"稳定",business:["国际择校","雅思托福","国际课程","留学规划"],style:["本地实用","考情内容","课程产品","学校资源"],moves:["一站式矩阵","择校探校","考情内容"],strategy:"以考培和国际学校择校获取本地家庭，再延伸到升学规划。",audience:"广州深圳国际教育家庭",cta:"择校/备考 → 测评 → 升学规划",opportunity:"跟踪本地搜索占位与低门槛产品。"},
 {name:"行知青藤教育集团",kind:"广州差异创新升学",tone:"purple",signals:11,trend:"升温",business:["AP/AL","差异创新升学","科研项目","AI教育"],style:["价值观叙事","反内卷","英雄成长","方法论"],moves:["英雄之旅","学校生态","差异创新升学"],strategy:"以使命感叙事占领差异化心智，构成学校、课程、科研生态。",audience:"重视个性成长的广州家庭",cta:"理念 → 成长诊断 → 生态产品",opportunity:"研究品牌语言与方法论命名。"},
 {name:"三皮匠",kind:"大湾区高端美本",tone:"orange",signals:8,trend:"待补充",business:["高端美本","长期规划","活动提升","文书申请"],style:["美本专精","本地服务","结果导向","精品顾问"],moves:["美本专精","大湾区服务","社媒待补充"],strategy:"以只做高端美本形成聚焦，依靠本地口碑与活动规划竞争。",audience:"大湾区目标美国名校家庭",cta:"专业内容 → 咨询 → 长线规划",opportunity:"补充顾问IP、讲座和报价证据。"}
];
export default function Competitors(){const [active,setActive]=useState(competitors[0]);return <main className="subpage"><header className="subnav"><a className="brand" href="/"><span className="mark">见</span><div>竞见<small>竞品外宣情报工作台</small></div></a><nav><a href="/">工作台</a><a href="/review">审核箱</a><a className="active" href="/competitors">竞品洞察</a></nav><span className="queue-count">更新至 07月12日</span></header><section className="page-title competitor-title"><div><span className="eyebrow">COMPETITOR INTELLIGENCE</span><h1>竞品机构洞察</h1><p>将全部已核实素材按机构归并，持续追踪业务布局、表达方式、营销动作与策略变化。</p></div><div className="review-stats"><b>8</b><span>监测机构</span><b>126</b><span>有效素材</span><b>3</b><span>策略变化</span></div></section><section className="competitor-shell"><aside className="competitor-list">{competitors.map(c=><button onClick={()=>setActive(c)} className={active.name===c.name?"active-card":""} key={c.name}><div className={`org ${c.tone}`}>{c.name[0]}</div><div><b>{c.name}</b><p>{c.kind} · {c.signals} 条有效素材</p></div><span>{c.trend}</span></button>)}</aside><div className="competitor-detail"><section className="profile-hero card"><div><span className="mini-tag">{active.kind}</span><h2>{active.name}</h2><p>{active.strategy}</p></div><div className="strategy-score"><small>本月信号强度</small><b>{active.signals}</b><span>条有效素材</span></div></section><div className="intelligence-grid"><article className="card"><span className="eyebrow">BUSINESS MAP</span><h3>业务内容与产品布局</h3><div className="keyword-cloud">{active.business.map(x=><span key={x}>{x}</span>)}</div><p><b>核心客群</b>{active.audience}</p></article><article className="card"><span className="eyebrow">COMMUNICATION STYLE</span><h3>外宣风格与表达特征</h3><div className="style-bars">{active.style.map((x,i)=><div key={x}><span>{x}</span><i style={{width:`${88-i*9}%`}}></i></div>)}</div></article><article className="card wide"><span className="eyebrow">MARKETING MOVES</span><h3>近期营销动作</h3><div className="move-timeline">{active.moves.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><small>{i===0?"重点动作":"持续观察"}</small></div>)}</div></article><article className="card"><span className="eyebrow">CONVERSION PATH</span><h3>推测转化路径</h3><p className="path-text">{active.cta}</p><small className="confidence-line">判断置信度：中高 · 基于CTA与活动入口</small></article><article className="card opportunity"><span className="eyebrow">IMPLICATION</span><h3>对我方的机会</h3><p>{active.opportunity}</p><a href="/review">查看支持此判断的原始素材 →</a></article></div><section className="source-ledger card"><div><h3>本机构证据账本</h3><p>所有结论均可回到原始来源</p></div><a href="/review">查看 {active.signals} 条链接与截图 →</a></section></div></section></main>}
