"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import AppShell from "../components/AppShell";

type Dashboard={kpis:Record<string,number>;recentMaterials:Array<Record<string,any>>;recentLeads:Array<Record<string,any>>;schemaReady:boolean};
type Competitor={id:string;name:string};
const empty={organization:"",title:"",sourceUrl:"",platform:"",publishedAt:"",rawText:"",note:"",focusPoints:""};
export default function Home(){
  const [dashboard,setDashboard]=useState<Dashboard|null>(null),[competitors,setCompetitors]=useState<Competitor[]>([]),[form,setForm]=useState(empty),[files,setFiles]=useState<File[]>([]),[preview,setPreview]=useState<Record<string,any>|null>(null),[loading,setLoading]=useState(""),[message,setMessage]=useState(""),[allowDuplicate,setAllowDuplicate]=useState(false),[packageUrl,setPackageUrl]=useState("");
  async function load(){const [d,c]=await Promise.all([fetch("/api/dashboard",{cache:"no-store"}).then(r=>r.json()),fetch("/api/competitors",{cache:"no-store"}).then(r=>r.json())]);setDashboard(d);setCompetitors(c.competitors||[])}useEffect(()=>{load().catch(()=>setMessage("读取数据失败，请查看系统设置。"))},[]);
  const set=(key:string,value:string)=>{setForm(v=>({...v,[key]:value}));setPreview(null)};
  async function doPreview(){setLoading("preview");setMessage("");const r=await fetch("/api/materials/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,hasAttachments:files.length>0})}),d=await r.json();setLoading("");if(!r.ok)return setMessage(d.error||"预览失败");setPreview(d.preview)}
  async function submit(analyze:boolean){if(!preview)return setMessage("请先完成入库预览和查重");setLoading(analyze?"analyze":"archive");setMessage("");const r=await fetch("/api/materials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,hasAttachments:files.length>0,allowDuplicate})}),d=await r.json();if(!r.ok){setLoading("");return setMessage(d.error||"写入失败")}for(let i=0;i<files.length;i++){const fd=new FormData();fd.append("file",files[i]);fd.append("materialId",d.material.id);fd.append("sortOrder",String(i));fd.append("isPrimary",String(i===0));const up=await fetch("/api/uploads",{method:"POST",body:fd});if(!up.ok){const e=await up.json();setLoading("");return setMessage(`素材已入库，但附件上传失败：${e.error}`)}}if(analyze){const a=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({materialId:d.material.id})}),ad=await a.json();if(!a.ok){setLoading("");return setMessage(`素材已入库，但分析失败：${ad.error}`)}setMessage(ad.mode==="ai"?"素材已入库并完成结构化AI分析。":`素材已入库并完成规则分析；内部AI状态：${ad.errorCode||"不可用"}。可导出外部AI分析包。`)}else setMessage("素材已成功加入正式素材库。");setForm(empty);setFiles([]);setPreview(null);setAllowDuplicate(false);setLoading("");await load()}
  async function exportPackage(){setLoading("package");const r=await fetch("/api/external-ai/export",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),d=await r.json();setLoading("");if(!r.ok)return setMessage(d.error||"分析包生成失败");setPackageUrl(d.downloadUrl);setMessage(`外部AI分析包已生成，共 ${d.counts.total} 条素材。`)}
  const k=dashboard?.kpis||{},cards=[
    ["本月新增素材",k.monthMaterials||0,"/materials?period=month"],["待审核线索",k.pendingLeads||0,"/review?status=pending"],["待分析素材",k.pendingAnalysis||0,"/materials?analysisStatus=pending"],["待人工复核",k.pendingHumanReview||0,"/analysis?humanReviewStatus=pending"],["正在监测机构",k.activeMonitors||0,"/monitoring"],["本月宣传事件",k.monthEvents||0,"/materials?view=events"],["分析失败/额度不足",k.analysisFailures||0,"/analysis?status=failed"],
  ];
  return <AppShell><section className="dashboard-hero"><div><span className="eyebrow">LIVE DATA WORKSPACE / 竞品外宣信号</span><h1>把每一条外宣，变成<br/><em>可追溯的市场情报_</em></h1><p>单条投递、批量导入和公开网络监测统一进入 Supabase；所有统计均来自当前真实数据。</p></div><div className="hero-actions"><button className="primary" onClick={()=>document.getElementById("submission")?.scrollIntoView()}>投递素材 →</button><a className="ghost button-link" href="/imports">批量导入</a><button className="ghost" onClick={exportPackage}>{loading==="package"?"正在打包…":"导出外部AI分析包"}</button>{packageUrl&&<a className="download-link" href={packageUrl}>下载最新分析包 ↓</a>}</div></section>
    {!dashboard?.schemaReady&&<div className="schema-warning">数据库仍是旧版结构。旧功能可继续使用；请在 Supabase 执行本次 migration 后启用完整状态、事件、报告和外部AI包。</div>}
    <section className="kpi-grid">{cards.map(([label,num,href])=><a className="kpi-card" href={String(href)} key={String(label)}><span>{label}</span><b>{num}</b><small>查看对应记录 →</small></a>)}</section>
    <section className="dashboard-grid" id="submission"><article className="card panel"><div className="panel-head"><div><span className="step">01</span><h2>单条素材投递</h2></div><span className="hint">先预览查重，再正式入库</span></div><div className="form-grid"><label><span>标准机构 *</span><input list="competitors" value={form.organization} onChange={e=>set("organization",e.target.value)} placeholder="选择或输入新机构"/><datalist id="competitors">{competitors.map(c=><option key={c.id}>{c.name}</option>)}</datalist></label><label><span>标题</span><input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="可在预览前人工修正"/></label><label><span>原始链接</span><input value={form.sourceUrl} onChange={e=>set("sourceUrl",e.target.value)} placeholder="小红书、公众号、官网等"/></label><label><span>平台</span><input value={form.platform} onChange={e=>set("platform",e.target.value)} placeholder="留空则按链接识别"/></label><label><span>发布时间</span><input type="datetime-local" value={form.publishedAt} onChange={e=>set("publishedAt",e.target.value)}/></label><label><span>截图或附件</span><input type="file" multiple accept="image/*,.pdf,.txt,.docx" onChange={e=>{setFiles(Array.from(e.target.files||[]));setPreview(null)}}/></label></div><label><span>原始正文</span><textarea value={form.rawText} onChange={e=>set("rawText",e.target.value)} placeholder="若链接无法抓取，可直接粘贴正文；系统不会伪造抓取结果。"/></label><div className="form-grid"><label><span>用户备注</span><textarea value={form.note} onChange={e=>set("note",e.target.value)} placeholder="补充你的观察"/></label><label><span>关注重点</span><textarea value={form.focusPoints} onChange={e=>set("focusPoints",e.target.value)} placeholder="例如产品包装、CTA、客群"/></label></div>{files.length>0&&<div className="file-list">{files.map(f=><span key={f.name}>{f.name}</span>)}</div>}{message&&<div className="notice">{message}</div>}<div className="actions"><button className="ghost" onClick={doPreview} disabled={Boolean(loading)}>{loading==="preview"?"正在识别与查重…":"预览并查重"}</button>{preview&&<><button className="ghost" onClick={()=>submit(false)} disabled={Boolean(loading)}>{loading==="archive"?"正在入库…":"确认入库"}</button><button className="primary" onClick={()=>submit(true)} disabled={Boolean(loading)}>{loading==="analyze"?"正在入库并分析…":"入库并分析"}</button></>}</div></article>
    <aside className="card panel preview-panel"><div className="panel-head"><div><span className="step">02</span><h2>入库预览</h2></div></div>{preview?<div className="preview-content"><dl><dt>识别机构</dt><dd>{preview.competitor?.name}{preview.competitor?.unmapped&&"（新机构）"}</dd><dt>标题 / 平台</dt><dd>{preview.title} · {preview.platform}</dd><dt>发布时间</dt><dd>{preview.publishedAt||"待核"}</dd><dt>原始链接</dt><dd className="break">{preview.sourceUrl||"无"}</dd><dt>建议标签</dt><dd>{preview.suggestedTags?.join("、")||"待人工标注"}</dd><dt>识别置信度</dt><dd>{Math.round((preview.confidence||0)*100)}%</dd></dl><div className={preview.duplicates?.length?"duplicate-box danger":"duplicate-box"}><b>{preview.duplicates?.length?`发现 ${preview.duplicates.length} 条重复/相似记录`:"未发现相同链接或正文哈希"}</b>{preview.duplicates?.map((x:Record<string,any>)=><a key={x.id} href={`/materials?id=${x.id}`}>{x.reason} · {x.title}</a>)}</div>{preview.duplicates?.length>0&&<label className="check-line"><input type="checkbox" checked={allowDuplicate} onChange={e=>setAllowDuplicate(e.target.checked)}/>仍作为独立素材入库</label>}</div>:<div className="empty-state"><b>尚未生成预览</b><p>填写机构，并提供链接、正文或附件后点击“预览并查重”。无法识别的字段会明确标记待核，不会伪造。</p></div>}</aside></section>
    <section className="dashboard-grid"><article className="card panel"><div className="panel-head"><div><span className="step">03</span><h2>最近入库素材</h2></div><a href="/materials">查看素材库 →</a></div><div className="compact-list">{dashboard?.recentMaterials?.map(m=><a href={`/materials?id=${m.id}`} key={m.id}><div><b>{m.competitors?.name||"未知机构"}</b><p>{m.title}</p></div><span>{m.platform||"待识别"} · {new Date(m.created_at).toLocaleDateString("zh-CN")}</span></a>)}{dashboard&&!dashboard.recentMaterials?.length&&<div className="empty-state"><b>暂无正式素材</b><p>先投递一条内容，或前往导入导出页面批量导入。</p></div>}</div></article><article className="card panel"><div className="panel-head"><div><span className="step">04</span><h2>最近监测线索</h2></div><a href="/review">进入审核箱 →</a></div><div className="compact-list">{dashboard?.recentLeads?.map(m=><a href={`/review?id=${m.id}`} key={m.id}><div><b>{m.competitors?.name||"未知机构"}</b><p>{m.title}</p></div><span>{m.status}</span></a>)}{dashboard&&!dashboard.recentLeads?.length&&<div className="empty-state"><b>暂无自动发现线索</b><p>创建监测任务并手动运行一次，结果会进入审核箱。</p><a href="/monitoring">创建监测任务 →</a></div>}</div></article></section>
  </AppShell>}
