"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import AppShell from "../../components/AppShell";
type R=Record<string,any>;
export default function Monitoring(){const[tasks,setTasks]=useState<R[]>([]),[competitors,setCompetitors]=useState<R[]>([]),[form,setForm]=useState({organization:"",region:"全国 + 广州及大湾区",keywords:"留学报告、产品升级、活动、合作",sources:["官网与新闻","高校合作公告","公开活动页"],frequency:"manual"}),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");async function load(){const[t,c]=await Promise.all([fetch("/api/monitors",{cache:"no-store"}).then(r=>r.json()),fetch("/api/competitors",{cache:"no-store"}).then(r=>r.json())]);setTasks(t.monitors||[]);setCompetitors(c.competitors||[])}useEffect(()=>{load()},[]);async function create(){setBusy("create");const r=await fetch("/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();setBusy("");setMsg(r.ok?"监测任务已创建。免费部署不做定时后台任务，请在需要时手动运行。":d.error);if(r.ok)await load()}async function run(task:R){setBusy(task.id);setMsg("正在搜索公开网络并保存线索…");const r=await fetch("/api/monitor/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.id,organization:task.competitors?.name,keywords:(task.keywords||[]).join("、"),region:task.region})}),d=await r.json();setBusy("");setMsg(r.ok?`监测完成：新增 ${d.discovered} 条，跳过重复 ${d.duplicates} 条。请进入审核箱。`:`监测失败（${d.code||"unknown_error"}）：${d.error||"未知错误"}。你仍可手动投递、批量导入或导出外部AI包。`);await load()}
return <AppShell title="监测任务" description="免费部署采用手动触发：系统只展示真实任务、真实运行日志和真实发现结果，不模拟定时运行。" actions={<a className="ghost button-link" href="/review">打开审核箱</a>}>
{msg&&<div className="notice">{msg}</div>}<section className="dashboard-grid"><article className="card panel"><div className="panel-head"><div><span className="step">01</span><h2>新增监测任务</h2></div></div><div className="form-grid"><label><span>竞品机构</span><input list="monitor-orgs" value={form.organization} onChange={e=>setForm(v=>({...v,organization:e.target.value}))}/><datalist id="monitor-orgs">{competitors.map(c=><option key={c.id}>{c.name}</option>)}</datalist></label><label><span>监测地区</span><input value={form.region} onChange={e=>setForm(v=>({...v,region:e.target.value}))}/></label><label className="full"><span>关键词</span><input value={form.keywords} onChange={e=>setForm(v=>({...v,keywords:e.target.value}))}/></label></div><label><span>公开信息源</span><div className="source-pills">{["官网与新闻","高校合作公告","公开活动页","招聘与组织变化"].map(s=><button key={s} className={form.sources.includes(s)?"selected":""} onClick={()=>setForm(v=>({...v,sources:v.sources.includes(s)?v.sources.filter(x=>x!==s):[...v.sources,s]}))}>{form.sources.includes(s)?"✓ ":"＋ "}{s}</button>)}</div></label><div className="actions"><button className="primary" disabled={busy==="create"||!form.organization} onClick={create}>{busy==="create"?"正在创建…":"创建任务"}</button></div></article><aside className="card panel"><h2>运行规则</h2><ul className="plain-list"><li>仅搜索公开网页；社交平台登录态内容仍建议上传链接与截图。</li><li>每次运行写入 monitoring_runs，并把结果放入审核箱。</li><li>OpenAI 未配置、额度不足或地区不可用时明确返回错误，不伪造发现。</li><li>没有付费后台服务时，电脑关机不影响网页使用；监测由你手动点击。</li></ul></aside></section>
<section className="card panel"><div className="panel-head"><div><span className="step">02</span><h2>任务与运行记录</h2></div><span>{tasks.filter(x=>x.enabled).length} 个启用任务</span></div><div className="monitor-task-grid">{tasks.map(task=>{const runs=(task.monitoring_runs||[]).sort((a:R,b:R)=>String(b.created_at).localeCompare(String(a.created_at))),last=runs[0];return <article key={task.id}><div><span className={`state-chip ${task.enabled?"":"muted"}`}>{task.enabled?"已启用":"已暂停"}</span><h3>{task.competitors?.name||"未知机构"}</h3><p>{(task.keywords||[]).join("、")||"无关键词"}</p><small>最近运行：{last?.started_at?new Date(last.started_at).toLocaleString("zh-CN"):task.last_run_at?new Date(task.last_run_at).toLocaleString("zh-CN"):"从未运行"}</small>{last&&<small>状态 {last.status} · 新增 {last.discovered_count||0} · 重复 {last.duplicate_count||0}{last.error_code?` · ${last.error_code}`:""}</small>}</div><div className="task-actions"><button className="ghost" onClick={async()=>{await fetch("/api/monitors",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:task.id,enabled:!task.enabled})});await load()}}>{task.enabled?"暂停":"启用"}</button><button className="primary" disabled={busy===task.id||!task.enabled} onClick={()=>run(task)}>{busy===task.id?"搜索中…":"立即运行"}</button></div></article>})}{!tasks.length&&<div className="empty-state"><b>暂无监测任务</b><p>先在上方选择机构和关键词创建任务；创建后手动运行一次。</p></div>}</div></section>
</AppShell>}
