"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import AppShell from "../../components/AppShell";
type Health=Record<string,any>;
export default function Settings(){const[health,setHealth]=useState<Health|null>(null),[settings,setSettings]=useState<Health[]>([]),[name,setName]=useState("default_report_title"),[value,setValue]=useState("留学竞品外宣监测月报"),[msg,setMsg]=useState("");async function load(){const[h,s]=await Promise.all([fetch("/api/health",{cache:"no-store"}).then(r=>r.json()),fetch("/api/settings",{cache:"no-store"}).then(r=>r.json())]);setHealth(h);setSettings(s.settings||[])}useEffect(()=>{load()},[]);async function save(){let parsed:any=value;try{parsed=JSON.parse(value)}catch{}const r=await fetch("/api/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({key:name,value:parsed})}),d=await r.json();setMsg(r.ok?"系统设置已保存。":d.error);if(r.ok)await load()}
return <AppShell title="系统设置" description="检查生产环境连接、数据库迁移和非敏感业务设置；任何密钥都只保存在 Vercel 服务端环境变量。">
{msg&&<div className="notice">{msg}</div>}<section className="settings-grid"><article className="card panel"><div className="panel-head"><div><span className="step">01</span><h2>运行健康检查</h2></div><span className={`state-chip ${health?.ok?"":"error"}`}>{health?.ok?"数据库已连接":"连接异常"}</span></div><dl className="settings-list"><dt>Supabase URL</dt><dd>{health?.configured?.supabaseUrl?"已配置":"缺失"}</dd><dt>Service Role</dt><dd>{health?.configured?.serviceRole?"已配置（仅服务端）":"缺失"}</dd><dt>Storage Bucket</dt><dd>{health?.configured?.storageBucket?"已配置":"使用默认 competitor-assets"}</dd><dt>OpenAI</dt><dd>{health?.configured?.openai?"已配置":"未配置；规则分析和外部AI包仍可用"}</dd><dt>数据库</dt><dd>{health?.database||"检查中"}</dd></dl><button className="ghost" onClick={load}>重新检查</button></article><article className="card panel"><div className="panel-head"><div><span className="step">02</span><h2>数据库迁移</h2></div></div><p>完整功能需要在 Supabase SQL Editor 执行：</p><code className="path-code">supabase/migrations/202607130001_p0_intelligence_refactor.sql</code><ul className="plain-list"><li>迁移保留旧表、旧字段和旧数据。</li><li>旧 discoveries、material_files、materials.analysis 会复制到新结构。</li><li>执行后刷新本页；总览不再显示旧结构提示。</li></ul></article><article className="card panel"><div className="panel-head"><div><span className="step">03</span><h2>非敏感业务设置</h2></div></div><div className="form-grid"><label><span>设置键</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>值（文本或JSON）</span><input value={value} onChange={e=>setValue(e.target.value)}/></label></div><button className="primary" onClick={save}>保存设置</button><div className="settings-table">{settings.map(s=><button key={s.key} onClick={()=>{setName(s.key);setValue(typeof s.value==="string"?s.value:JSON.stringify(s.value))}}><b>{s.key}</b><span>{typeof s.value==="string"?s.value:JSON.stringify(s.value)}</span></button>)}{!settings.length&&<p>暂无自定义设置。迁移未执行时此列表也会为空。</p>}</div></article><article className="card panel"><div className="panel-head"><div><span className="step">04</span><h2>环境变量清单</h2></div></div><ul className="plain-list"><li><code>SUPABASE_URL</code>：项目根地址，不包含 <code>/rest/v1</code></li><li><code>SUPABASE_SERVICE_ROLE_KEY</code>：仅服务端</li><li><code>SUPABASE_STORAGE_BUCKET</code>：默认 competitor-assets</li><li><code>OPENAI_API_KEY</code>：可选；缺失时自动降级</li><li><code>OPENAI_MODEL</code>：可选，默认 gpt-5.6-terra</li></ul><p className="help-text">不要在浏览器、本仓库或导出文件中放入真实密钥。</p></article></section>
</AppShell>}
