"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useState} from "react";
import AppShell from "../../components/AppShell";
type Row=Record<string,any>;
const fields=[['organization','机构名称'],['sourceUrl','链接'],['rawText','正文'],['publishedAt','发布时间'],['platform','平台'],['title','标题'],['note','备注'],['focusPoints','关注重点']];
export default function Imports(){const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Row|null>(null),[mapping,setMapping]=useState<Record<string,string|null>>({}),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[mode,setMode]=useState("skip"),[externalFile,setExternalFile]=useState<File|null>(null),[externalModel,setExternalModel]=useState("ChatGPT"),[externalResult,setExternalResult]=useState<Row|null>(null),[packageUrl,setPackageUrl]=useState("");async function inspect(custom?:Record<string,string|null>){if(!file)return setMsg("请选择CSV或Excel文件");setBusy("preview");const fd=new FormData();fd.append("file",file);if(custom)fd.append("mapping",JSON.stringify(custom));const r=await fetch("/api/imports/preview",{method:"POST",body:fd}),d=await r.json();setBusy("");if(!r.ok)return setMsg(d.error||"预览失败");setPreview(d);setMapping(d.mapping||{});setMsg("导入预览已生成；请检查字段映射、错误行和重复记录。")}
async function commit(){if(!preview)return;setBusy("commit");const r=await fetch("/api/imports/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jobId:preview.job.id,rows:preview.rows,duplicateMode:mode})}),d=await r.json();setBusy("");setMsg(r.ok?`导入完成：成功 ${d.summary.success}，跳过 ${d.summary.skipped}，合并 ${d.summary.merged}，失败 ${d.summary.failed}。`:d.error);if(r.ok)setPreview((v:Row)=>({...v,commitSummary:d.summary}))}
function errorsCsv(){if(!preview)return;const rows=preview.rows.filter((x:Row)=>x.errors.length),text=['行号,错误,原始数据',...rows.map((x:Row)=>`${x.rowNumber},"${x.errors.join('；').replaceAll('"','""')}","${JSON.stringify(x.raw).replaceAll('"','""')}"`)].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download='导入错误行.csv';a.click();URL.revokeObjectURL(a.href)}
async function importExternal(){if(!externalFile)return setMsg("请选择外部AI回填文件");setBusy("external");const fd=new FormData();fd.append("file",externalFile);fd.append("modelName",externalModel);fd.append("conflictMode","keep_both");const r=await fetch("/api/external-ai/import",{method:"POST",body:fd}),d=await r.json();setBusy("");if(!r.ok)return setMsg(d.error||"回填失败");setExternalResult(d.summary);setMsg("外部AI分析已作为独立版本导入，没有覆盖原始素材或已有分析。")}
async function pack(){setBusy("pack");const r=await fetch("/api/external-ai/export",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(preview?.job?.id?{importJobId:preview.job.id}:{})}),d=await r.json();setBusy("");if(!r.ok)return setMsg(d.error||"生成失败");setPackageUrl(d.downloadUrl);setMsg(`交接包已生成，共 ${d.counts.total} 条素材。`)}
return <AppShell title="导入导出" description="CSV / Excel 分批校验入库；内部AI不可用时生成完整外部AI交接包，并将外部结果作为独立版本回填。" actions={<button className="ghost" onClick={pack}>{busy==="pack"?"打包中…":"导出外部AI分析包"}</button>}>
{msg&&<div className="notice">{msg}{packageUrl&&<>　<a href={packageUrl}>下载ZIP ↓</a></>}</div>}<section className="dashboard-grid"><article className="card panel"><div className="panel-head"><div><span className="step">01</span><h2>批量导入素材</h2></div><span className="hint">CSV / XLSX，最大15MB</span></div><label><span>选择文件</span><input type="file" accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/></label><p className="help-text">最低字段：机构名称；并且链接、正文或附件至少一种。单行错误不会阻止其他行导入。</p><div className="actions"><button className="primary" disabled={!file||busy==="preview"} onClick={()=>inspect()}>{busy==="preview"?"正在解析与查重…":"上传并生成预览"}</button></div></article><aside className="card panel"><div className="panel-head"><div><span className="step">02</span><h2>外部AI结果回填</h2></div></div><label><span>外部模型名称</span><input value={externalModel} onChange={e=>setExternalModel(e.target.value)}/></label><label><span>回填文件</span><input type="file" accept=".xlsx,.json" onChange={e=>setExternalFile(e.target.files?.[0]||null)}/></label><p className="help-text">按素材编号或证据编号匹配；冲突默认两个版本并存。</p><button className="primary" disabled={!externalFile||busy==="external"} onClick={importExternal}>{busy==="external"?"正在匹配与导入…":"导入外部分析结果"}</button>{externalResult&&<div className="result-grid"><span>匹配 <b>{externalResult.matched}</b></span><span>未匹配 <b>{externalResult.unmatched}</b></span><span>新增 <b>{externalResult.created}</b></span><span>冲突 <b>{externalResult.conflicts}</b></span><span>错误 <b>{externalResult.errors}</b></span></div>}</aside></section>
{preview&&<><section className="card panel"><div className="panel-head"><div><span className="step">03</span><h2>字段映射</h2></div><span>任务 {preview.job.id}</span></div><div className="mapping-grid">{fields.map(([key,label])=><label key={key}><span>{label}</span><select value={mapping[key]||""} onChange={e=>setMapping(v=>({...v,[key]:e.target.value||null}))}><option value="">不导入</option>{preview.headers.map((h:string)=><option value={h} key={h}>{h}</option>)}</select></label>)}</div><button className="ghost" onClick={()=>inspect(mapping)}>按新映射重新预览</button></section><section className="summary-strip import-summary"><span><b>{preview.summary.total}</b> 总行数</span><span><b>{preview.summary.valid}</b> 有效</span><span><b>{preview.summary.invalid}</b> 错误</span><span><b>{preview.summary.duplicates}</b> 疑似重复</span><span><b>{preview.summary.unmappedCompetitors}</b> 新机构</span></section><section className="card"><div className="table-wrap import-table"><table><thead><tr><th>行</th><th>机构</th><th>标题 / 链接</th><th>机构映射</th><th>重复</th><th>校验结果</th></tr></thead><tbody>{preview.rows.map((x:Row)=><tr key={x.rowNumber} className={x.errors.length?"row-error":""}><td>{x.rowNumber}</td><td>{x.normalized.organization||"—"}</td><td><b>{x.normalized.title||"未填写标题"}</b><p>{x.normalized.sourceUrl||x.normalized.rawText?.slice(0,80)||"—"}</p></td><td>{x.competitor?.name||"将创建新机构"}</td><td>{x.duplicates.length?x.duplicates.map((d:Row)=><span className="duplicate-label" key={d.id}>{d.reason}</span>):"无"}</td><td>{x.errors.length?<span className="error-text">{x.errors.join("；")}</span>:"通过"}</td></tr>)}</tbody></table></div><div className="import-actions"><label><span>重复处理</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="skip">跳过重复</option><option value="merge">标记合并到已有素材</option><option value="import">仍作为独立素材导入</option></select></label><button className="ghost" onClick={errorsCsv} disabled={!preview.summary.invalid}>下载错误行</button><button className="primary" disabled={busy==="commit"} onClick={commit}>{busy==="commit"?"正在分行写入…":"确认批量入库"}</button>{preview.commitSummary&&<button className="ghost" onClick={pack}>导出本批次外部AI包</button>}</div></section></>}
</AppShell>}
