import {getSupabaseAdmin,describeSupabaseError} from "../../../../lib/supabase-admin";
import {parseXlsx} from "../../../../lib/xlsx";

const arr=(v:unknown)=>Array.isArray(v)?v.map(String):String(v||"").split(/[；;,\n]/).map(x=>x.trim()).filter(Boolean);
export async function POST(req:Request){
  try{
    const form=await req.formData(),file=form.get("file"),modelName=String(form.get("modelName")||"external-ai"),conflictMode=String(form.get("conflictMode")||"keep_both");if(!(file instanceof File))return Response.json({error:"请选择回填Excel或JSON"},{status:400});if(file.size>15*1024*1024)return Response.json({error:"回填文件不能超过15MB"},{status:400});
    let rows:Record<string,unknown>[];if(file.name.toLowerCase().endsWith(".json")){const parsed=JSON.parse(await file.text());rows=Array.isArray(parsed)?parsed:Array.isArray(parsed.analyses)?parsed.analyses:[]}else if(file.name.toLowerCase().endsWith(".xlsx")){const matrix=await parseXlsx(await file.arrayBuffer()),headers=matrix.shift()||[];rows=matrix.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||""])))}else return Response.json({error:"仅支持 .xlsx 或 .json"},{status:400});
    const sb=getSupabaseAdmin(),job=await sb.from("external_ai_imports").insert({filename:file.name,model_name:modelName,status:"processing",conflict_mode:conflictMode}).select().single();if(job.error)throw job.error;
    const summary={matched:0,unmatched:0,created:0,conflicts:0,errors:0,details:[] as Array<Record<string,unknown>>};
    for(let i=0;i<rows.length;i++){try{const row=rows[i],materialId=String(row.material_id||row["素材编号"]||""),evidenceId=String(row.evidence_id||row["证据编号"]||""),material=materialId?await sb.from("materials").select("id,evidence_id").eq("id",materialId).maybeSingle():await sb.from("materials").select("id,evidence_id").eq("evidence_id",evidenceId).maybeSingle();if(!material.data){summary.unmatched++;summary.details.push({row:i+2,status:"unmatched",materialId,evidenceId});continue}summary.matched++;const source=`external:${modelName}`,existing=await sb.from("analysis_results").select("id,current_version").eq("material_id",material.data.id).eq("source",source).maybeSingle();if(existing.data){summary.conflicts++;if(conflictMode==="keep_original"){summary.details.push({row:i+2,status:"conflict_skipped"});continue}}
      const result=existing.data?existing:await sb.from("analysis_results").insert({material_id:material.data.id,source,status:"completed",current_version:0}).select("id,current_version").single();if(result.error)throw result.error;const version=Number(result.data!.current_version||0)+1,structured={facts:{products:arr(row.product_direction||row["产品方向"]),activities:[],prices:[],offers:[],audiences:arr(row.target_audiences||row["目标客群"]),regions:[],results:[],people:[],ctas:[],promises:[]},content_tags:arr(row.content_tags||row["内容标签"]),marketing_strategies:arr(row.marketing_strategies||row["营销策略"]),target_audiences:arr(row.target_audiences||row["目标客群"]),conversion_path:arr(row.conversion_path||row["转化路径"]),strategy_signals:arr(row.strategy_signals||row["竞品策略信号"]),actions:arr(row.actions||row["行动建议"]),risk_notes:arr(row.risk_notes||row["风险提示"]),evidence_ids:arr(row.evidence_ids||row["支持证据"]||material.data.evidence_id),confidence:Number(row.confidence||row["置信度"]||0.5)};
      const created=await sb.from("analysis_versions").insert({analysis_result_id:result.data!.id,version,model_name:String(row.external_model||row["外部模型名称"]||modelName),prompt_version:"external-import-v1",structured_data:structured,facts:structured.facts,inferences:{content_tags:structured.content_tags,marketing_strategies:structured.marketing_strategies,target_audiences:structured.target_audiences,conversion_path:structured.conversion_path,strategy_signals:structured.strategy_signals,risk_notes:structured.risk_notes},actions:{items:structured.actions},confidence:structured.confidence,status:"completed",human_review_status:"pending"}).select("id").single();if(created.error)throw created.error;await sb.from("analysis_results").update({current_version:version,status:"completed"}).eq("id",result.data!.id);if(structured.evidence_ids.length)await sb.from("analysis_evidence").insert(structured.evidence_ids.map(e=>({analysis_version_id:created.data.id,material_id:material.data!.id,evidence_id:e})));await sb.from("materials").update({analysis_status:"completed",human_review_status:"pending"}).eq("id",material.data.id);summary.created++}catch(error){summary.errors++;summary.details.push({row:i+2,status:"error",message:describeSupabaseError(error)})}}
    await sb.from("external_ai_imports").update({status:summary.errors?"partial":"completed",matched_count:summary.matched,unmatched_count:summary.unmatched,created_count:summary.created,conflict_count:summary.conflicts,error_count:summary.errors}).eq("id",job.data.id);
    return Response.json({importId:job.data.id,summary});
  }catch(error){return Response.json({error:describeSupabaseError(error)},{status:500})}
}
