import {getSupabaseAdmin,describeSupabaseError} from "../../../../../lib/supabase-admin";
import {createXlsx} from "../../../../../lib/xlsx";

export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){
  try{
    const {id}=await params,format=new URL(req.url).searchParams.get("format")||"markdown",sb=getSupabaseAdmin(),project=await sb.from("report_projects").select("*,report_material_links(material_id,citation_order)").eq("id",id).single();if(project.error)throw project.error;
    const links=(project.data.report_material_links||[]) as Array<{material_id:string;citation_order:number}>,ids=links.map(x=>x.material_id);let q=sb.from("materials").select("*,competitors(name),analysis_results(*,analysis_versions(*))").is("deleted_at",null).gte("created_at",project.data.period_start).lte("created_at",`${project.data.period_end}T23:59:59.999Z`).order("created_at",{ascending:true});if(ids.length)q=q.in("id",ids);else if(project.data.competitor_ids?.length)q=q.in("competitor_id",project.data.competitor_ids);if(project.data.reviewed_only)q=q.in("human_review_status",["reviewed","modified","not_required"]);const {data,error}=await q.limit(1000);if(error)throw error;const materials=data||[],summary={report:{id:project.data.id,name:project.data.name,period_start:project.data.period_start,period_end:project.data.period_end,version:project.data.version},quality:{material_count:materials.length,with_source:materials.filter(x=>x.source_url||x.raw_text).length,reviewed:materials.filter(x=>["reviewed","modified","not_required"].includes(x.human_review_status)).length,analyzed:materials.filter(x=>x.analysis_status==="completed").length},materials};
    if(format==="json")return new Response(JSON.stringify(summary,null,2),{headers:{"content-type":"application/json; charset=utf-8","content-disposition":`attachment; filename="report-${id}.json"`}});
    if(format==="excel"){const rows=[["证据编号","机构","标题","平台","发布时间","原始链接","分析状态","人工复核","报告状态"],...materials.map(x=>[x.evidence_id,x.competitors?.name||x.original_organization,x.title,x.platform,x.published_at,x.source_url,x.analysis_status,x.human_review_status,x.report_status])];const bytes=await createXlsx("报告素材",rows);return new Response(Buffer.from(bytes),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="report-${id}.xlsx"`}})}
    const body=`# ${project.data.name}\n\n- 周期：${project.data.period_start} 至 ${project.data.period_end}\n- 报告版本：${project.data.version}\n- 选用素材：${materials.length} 条\n- 已分析：${summary.quality.analyzed} 条\n- 已复核：${summary.quality.reviewed} 条\n\n## 数据质量检查\n${materials.length?"素材已载入；所有结论必须引用下列证据编号。":"当前范围没有素材，请返回报告项目补充选择。"}\n\n## 证据素材\n${materials.map(x=>`### ${x.evidence_id}｜${x.competitors?.name||x.original_organization||"未知机构"}\n- ${x.title}\n- 平台/时间：${x.platform||"待识别"} / ${x.published_at||"待核"}\n- 原始链接：${x.source_url||"无"}\n- 原始正文：${x.raw_text||"未采集"}`).join("\n\n")}`;return new Response(body,{headers:{"content-type":"text/markdown; charset=utf-8","content-disposition":`attachment; filename="report-${id}.md"`}})
  }catch(error){return Response.json({error:describeSupabaseError(error)},{status:500})}
}

