"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, @next/next/no-img-element */
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import AppShell from "../../components/AppShell";
import {stateLabels} from "../../lib/domain";

type M=Record<string,any>;
export default function MaterialsPage(){
  const [materials,setMaterials]=useState<M[]>([]),[competitors,setCompetitors]=useState<M[]>([]),[events,setEvents]=useState<M[]>([]),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<M|null>(null),[loading,setLoading]=useState(""),[message,setMessage]=useState(""),[view,setView]=useState("materials"),[filters,setFilters]=useState({q:"",competitor:"",platform:"",analysisStatus:"",reviewStatus:""}),[packageUrl,setPackageUrl]=useState("");
  async function load(){const params=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const [m,c,e]=await Promise.all([fetch(`/api/materials?${params}`,{cache:"no-store"}).then(r=>r.json()),fetch("/api/competitors",{cache:"no-store"}).then(r=>r.json()),fetch("/api/events",{cache:"no-store"}).then(r=>r.json())]);setMaterials(m.materials||[]);setCompetitors(c.competitors||[]);setEvents(e.events||[])}useEffect(()=>{const q=new URLSearchParams(location.search),id=q.get("id");setView(q.get("view")==="events"?"events":"materials");setFilters(v=>({...v,analysisStatus:q.get("analysisStatus")||""}));load();if(id)fetch(`/api/materials/${id}`).then(r=>r.json()).then(d=>d.material&&setDetail(d.material))},[]);
  const platforms=useMemo(()=>[...new Set(materials.map(x=>x.platform).filter(Boolean))], [materials]);
  async function open(id:string){setLoading("detail");const d=await fetch(`/api/materials/${id}`).then(r=>r.json());setLoading("");if(d.material)setDetail(d.material);else setMessage(d.error||"读取详情失败")}
  async function batch(changes:Record<string,unknown>,action?:string){if(!selected.length)return setMessage("请先选择素材");setLoading("batch");const r=await fetch("/api/materials",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ids:selected,changes,action})}),d=await r.json();setLoading("");setMessage(r.ok?`已更新 ${d.updated} 条素材`:d.error);if(r.ok){setSelected([]);await load()}}
  async function analyze(){if(!selected.length)return setMessage("请先选择素材");setLoading("analyze");let ok=0,failed=0;for(const id of selected){const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({materialId:id})});if(r.ok)ok++;else failed++}setLoading("");setMessage(`分析完成：成功 ${ok}，失败 ${failed}。失败或额度不足可导出外部AI包。`);await load()}
  async function exportPackage(){setLoading("export");const r=await fetch("/api/external-ai/export",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ids:selected.length?selected:undefined})}),d=await r.json();setLoading("");if(!r.ok)return setMessage(d.error||"导出失败");setPackageUrl(d.downloadUrl);setMessage(`已生成 ${d.counts.total} 条素材的外部AI交接包。`)}
  return <AppShell title="素材库" description="正式素材、附件、状态、事件与分析证据统一从 Supabase 读取。" actions={<><button className="ghost" onClick={()=>setView(view==="materials"?"events":"materials")}>{view==="materials"?"查看宣传事件":"返回素材"}</button><a className="primary button-link" href="/imports">批量导入</a></>}>
    {message&&<div className="notice">{message}{packageUrl&&<>　<a href={packageUrl}>下载分析包 ↓</a></>}</div>}
    {view==="events"?<section className="card panel"><div className="panel-head"><div><h2>宣传事件</h2><p>一个事件可关联官网、公众号、媒体转载和活动页等多条素材。</p></div><button className="primary" onClick={async()=>{const name=prompt("宣传事件名称");if(!name)return;await fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,confirmed:true})});await load()}}>新建事件</button></div><div className="table-wrap"><table><thead><tr><th>事件编号</th><th>事件名称</th><th>主机构</th><th>类型</th><th>开始时间</th><th>关联素材</th><th>确认状态</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.event_code}</td><td><b>{e.name}</b></td><td>{e.competitors?.name||"待确认"}</td><td>{e.event_type||"待分类"}</td><td>{e.start_at?new Date(e.start_at).toLocaleDateString("zh-CN"):"待核"}</td><td>{e.material_event_links?.length||0}</td><td>{e.confirmation_status}</td></tr>)}</tbody></table>{!events.length&&<div className="empty-state"><b>暂无宣传事件</b><p>从审核箱确认线索时创建事件，或在这里手动新建。</p></div>}</div></section>:<>
    <section className="card filter-bar"><input value={filters.q} onChange={e=>setFilters(v=>({...v,q:e.target.value}))} placeholder="搜索标题或正文"/><select value={filters.competitor} onChange={e=>setFilters(v=>({...v,competitor:e.target.value}))}><option value="">全部机构</option>{competitors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={filters.platform} onChange={e=>setFilters(v=>({...v,platform:e.target.value}))}><option value="">全部平台</option>{platforms.map(x=><option key={x}>{x}</option>)}</select><select value={filters.analysisStatus} onChange={e=>setFilters(v=>({...v,analysisStatus:e.target.value}))}><option value="">全部分析状态</option>{["pending","processing","completed","failed","quota_exceeded","model_unavailable"].map(x=><option key={x} value={x}>{stateLabels[x]}</option>)}</select><select value={filters.reviewStatus} onChange={e=>setFilters(v=>({...v,reviewStatus:e.target.value}))}><option value="">全部审核状态</option>{["pending","approved","ignored","merged"].map(x=><option key={x} value={x}>{stateLabels[x]}</option>)}</select><button className="primary" onClick={load}>应用筛选</button><button className="ghost" onClick={()=>{setFilters({q:"",competitor:"",platform:"",analysisStatus:"",reviewStatus:""});setTimeout(load)}}>清除</button></section>
    <section className="batch-bar"><span>已选择 {selected.length} 条</span><button onClick={analyze} disabled={loading==="analyze"}>{loading==="analyze"?"分析中…":"重新分析"}</button><button onClick={()=>batch({report_status:"selected"})}>加入报告</button><button onClick={()=>batch({},"delete")}>软删除</button><button onClick={exportPackage} disabled={loading==="export"}>{loading==="export"?"正在打包…":"导出外部AI包"}</button></section>
    <section className="card"><div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={selected.length===materials.length&&materials.length>0} onChange={e=>setSelected(e.target.checked?materials.map(x=>x.id):[])}/></th><th>证据 / 机构 / 内容</th><th>平台</th><th>发布时间</th><th>采集/审核</th><th>分析/复核</th><th>报告</th><th></th></tr></thead><tbody>{materials.map(m=><tr key={m.id}><td><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,m.id]:v.filter(x=>x!==m.id))}/></td><td><small className="evidence-code">{m.evidence_id||"迁移后生成"}</small><b className="table-title">{m.competitors?.name||m.original_organization||"未知机构"}</b><p>{m.title}</p></td><td>{m.platform||"待识别"}</td><td>{m.published_at?new Date(m.published_at).toLocaleDateString("zh-CN"):"待核"}</td><td><span className="state-chip">{stateLabels[m.collection_status]||m.collection_status||"已识别"}</span><br/><small>{stateLabels[m.review_status]||m.review_status||"已入库"}</small></td><td><span className={`state-chip ${["failed","quota_exceeded","model_unavailable"].includes(m.analysis_status)?"error":""}`}>{stateLabels[m.analysis_status]||m.status||"待分析"}</span><br/><small>{stateLabels[m.human_review_status]||m.human_review_status||"待复核"}</small></td><td>{stateLabels[m.report_status]||m.report_status||"未使用"}</td><td><button className="text-btn" onClick={()=>open(m.id)}>详情 →</button></td></tr>)}</tbody></table>{!materials.length&&<div className="empty-state"><b>当前筛选下没有素材</b><p>可能尚未入库，或筛选条件过窄。清除筛选，或投递/批量导入素材。</p><Link href="/">去投递素材 →</Link></div>}</div></section></>}
    {detail&&<div className="overlay" onClick={()=>setDetail(null)}><article className="detail-drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><span className="evidence-code">{detail.evidence_id}</span><h2>{detail.title}</h2><p>{detail.competitors?.name} · {detail.platform} · {detail.published_at||"日期待核"}</p><div className="detail-actions">{detail.source_url&&<a className="primary button-link" target="_blank" rel="noreferrer" href={detail.source_url}>打开原始链接 ↗</a>}</div><section><h3>原始正文</h3><div className="raw-text">{detail.raw_text||"未采集正文，请查看附件或原始链接。"}</div></section><section><h3>附件证据</h3><div className="asset-grid">{detail.assets?.map((a:M)=><a key={a.id} href={a.url} target="_blank" rel="noreferrer">{a.mime_type?.startsWith("image/")&&<img alt={a.filename} src={a.url}/>}<span>{a.filename}</span></a>)}{!detail.assets?.length&&<p>没有附件。</p>}</div></section><section><h3>分析历史版本</h3>{detail.analysis_results?.flatMap((r:M)=>r.analysis_versions||[]).map((v:M)=><div className="analysis-version" key={v.id}><b>{v.model_name||"未知模型"} · v{v.version}</b><span>{v.status} · 置信度 {v.confidence??"待核"}</span><pre>{JSON.stringify(v.structured_data,null,2)}</pre></div>)}{!detail.analysis_results?.length&&<p>尚无结构化分析版本。</p>}</section></article></div>}
  </AppShell>}
