import JSZip from "jszip";
import {getSupabaseAdmin,describeSupabaseError,storageBucket} from "../../../../lib/supabase-admin";
import {createXlsx} from "../../../../lib/xlsx";

const cleanName=(x:string)=>x.replace(/[\\/:*?"<>|]/g,"_").slice(0,80);
export async function POST(req:Request){
  const sb=getSupabaseAdmin();let exportId:string|undefined;
  try{
    const filters=await req.json() as {ids?:string[];from?:string;to?:string;competitorIds?:string[];analysisStatus?:string;importJobId?:string;reportProjectId?:string},job=await sb.from("export_jobs").insert({export_type:"external_ai_package",status:"processing",filters}).select().single();if(job.error)throw job.error;exportId=job.data.id;
    let q=sb.from("materials").select("*,competitors(name,english_name,competitor_aliases(alias)),material_assets(*),analysis_results(*,analysis_versions(*)),material_event_links(marketing_events(event_code,name))").is("deleted_at",null).order("created_at",{ascending:true}).limit(1000);
    if(filters.ids?.length)q=q.in("id",filters.ids);if(filters.from)q=q.gte("created_at",filters.from);if(filters.to)q=q.lte("created_at",filters.to);if(filters.competitorIds?.length)q=q.in("competitor_id",filters.competitorIds);if(filters.analysisStatus)q=q.eq("analysis_status",filters.analysisStatus);if(filters.importJobId)q=q.eq("import_job_id",filters.importJobId);
    const {data,error}=await q;if(error)throw error;const materials=(data||[]) as Array<Record<string,unknown>>;if(!materials.length)throw new Error("当前范围没有可导出的素材");
    const zip=new JSZip(),now=new Date(),stamp=now.toISOString().replace(/[-:T]/g,"").slice(0,12),folder=zip.folder(`竞对外宣分析包_${stamp}`)!;
    const counts={new:materials.filter(m=>m.is_new).length,history:materials.filter(m=>!m.is_new).length,duplicates:materials.filter(m=>m.duplicate_of).length,total:materials.length};
    folder.file("README.md",`# 竞对外宣分析交接包\n\n## 项目背景\n本数据包来自“竞见｜竞品外宣情报工作台”，用于在内部模型不可用、额度不足或用户主动选择其他模型时继续分析。\n\n## 数据范围\n- 生成时间：${now.toISOString()}\n- 本次新增：${counts.new} 条\n- 历史素材：${counts.history} 条\n- 疑似重复：${counts.duplicates} 条\n- 最终导出：${counts.total} 条\n\n## 文件结构\n- AI分析任务指令.md：可直接复制给外部AI\n- 素材明细.xlsx / .md / 素材数据.json：同一批证据的三种格式\n- 机构背景资料.md：机构基础信息\n- 已有分析结果.xlsx：内部AI、规则或人工历史版本\n- 外部AI分析回填模板.xlsx：请外部AI按列输出\n- 证据索引.xlsx：证据编号与原始来源映射\n- assets/：已入库附件\n\n## 使用方法\n1. 将整个ZIP解压后上传给 ChatGPT、Claude、Gemini、DeepSeek 或其他模型。\n2. 复制“AI分析任务指令.md”作为任务说明。数据过大时按机构或时间拆分，但必须保留证据编号。\n3. 要求模型填写“外部AI分析回填模板.xlsx”或输出同字段JSON。\n4. 回到工作台“导入导出”页面导入结果。\n\n## 数据口径与限制\n素材条数不等于宣传事件数；转载或多平台内容可能属于同一事件。不得虚构未提供的信息，原文不足时必须标记“样本不足/待验证”。`);
    folder.file("AI分析任务指令.md",`# 外部AI分析任务\n\n请读取本包全部素材并完成结构化竞品外宣分析。\n\n必须遵守：\n1. 严格区分原始事实、合理推断和行动建议，不得虚构。\n2. 每个关键结论引用一个或多个证据编号（EVD-...）。\n3. 样本不足时明确说明，不把单条内容外推为机构长期策略。\n4. 分析整体趋势与机构差异，识别产品、客群、主题、营销策略、转化路径、近期变化与异常信号。\n5. 给出我方可执行的外宣、产品包装与服务优化建议。\n6. 按“外部AI分析回填模板.xlsx”字段输出；也可返回JSON数组，字段名使用模板英文键。\n7. 置信度用0-1小数，支持证据用证据编号数组。`);
    const headers=["素材编号","证据编号","机构","机构别名","平台","标题","发布时间","原始链接","原始正文","附件文件名","来源方式","内容类型","已有标签","已有AI分析","人工备注","是否本次新增","导入批次","疑似重复","关联宣传事件"];
    const detailRows=materials.map(m=>{const c=m.competitors as Record<string,unknown>|null,assets=(m.material_assets||[]) as Array<Record<string,unknown>>,analyses=(m.analysis_results||[]) as Array<Record<string,unknown>>,events=(m.material_event_links||[]) as Array<Record<string,unknown>>;return[m.id,m.evidence_id,(c?.name||m.original_organization),((c?.competitor_aliases||[]) as Array<Record<string,unknown>>).map(a=>a.alias).join("；"),m.platform,m.title,m.published_at,m.source_url,m.raw_text,assets.map(a=>a.filename).join("；"),m.source_type,m.content_type,[m.tag,...((m.theme_tags||[]) as unknown[])].filter(Boolean).join("；"),JSON.stringify(analyses),m.note,m.is_new?"是":"否",m.import_job_id,m.duplicate_of?"是":"否",events.map(e=>(e.marketing_events as Record<string,unknown>|null)?.name).filter(Boolean).join("；")]});
    folder.file("素材明细.xlsx",await createXlsx("素材明细",[headers,...detailRows]));
    const md=materials.map(m=>{const c=m.competitors as Record<string,unknown>|null,assets=(m.material_assets||[]) as Array<Record<string,unknown>>;return`## ${m.evidence_id}｜${c?.name||m.original_organization||"未知机构"}\n- 素材编号：${m.id}\n- 发布时间：${m.published_at||"待核"}\n- 平台：${m.platform||"待识别"}\n- 标题：${m.title}\n- 原始链接：${m.source_url||"无"}\n- 附件：${assets.map(a=>a.filename).join("、")||"无"}\n- 已有标签：${[m.tag,...((m.theme_tags||[]) as unknown[])].filter(Boolean).join("、")||"无"}\n- 人工备注：${m.note||"无"}\n- 是否本次新增：${m.is_new?"是":"否"}\n\n### 原始正文\n${m.raw_text||"未采集正文，请结合截图或链接。"}`}).join("\n\n---\n\n");folder.file("素材明细.md",`# 素材明细\n\n${md}`);
    folder.file("素材数据.json",JSON.stringify({schema_version:"1.0",generated_at:now.toISOString(),counts,materials},null,2));
    const competitorMap=new Map<string,{name:string;english:string;count:number}>();materials.forEach(m=>{const c=m.competitors as Record<string,unknown>|null,key=String(m.competitor_id||c?.name||m.original_organization);const current=competitorMap.get(key)||{name:String(c?.name||m.original_organization||"未知机构"),english:String(c?.english_name||""),count:0};current.count++;competitorMap.set(key,current)});folder.file("机构背景资料.md",`# 机构背景资料\n\n${[...competitorMap.values()].map(x=>`## ${x.name}${x.english?`（${x.english}）`:""}\n- 本包有效素材：${x.count} 条\n- 更详细定位请以素材证据和工作台机构主数据为准。`).join("\n\n")}`);
    const analysisRows=materials.flatMap(m=>((m.analysis_results||[]) as Array<Record<string,unknown>>).flatMap(result=>((result.analysis_versions||[]) as Array<Record<string,unknown>>).map(v=>[m.id,m.evidence_id,result.source,v.version,v.model_name,v.created_at,v.confidence,v.human_review_status,v.status,v.error_code,JSON.stringify(v.structured_data)])));
    folder.file("已有分析结果.xlsx",await createXlsx("已有分析",[["素材编号","证据编号","分析来源","版本","模型","分析时间","置信度","人工复核状态","分析状态","错误码","结构化结果"],...analysisRows]));
    const fillHeaders=["material_id","evidence_id","content_tags","product_direction","target_audiences","marketing_strategies","conversion_path","strategy_signals","risk_notes","actions","confidence","evidence_ids","external_model","analyzed_at","human_note"];
    folder.file("外部AI分析回填模板.xlsx",await createXlsx("外部AI回填",[fillHeaders,...materials.map(m=>[m.id,m.evidence_id,"","","","","","","","","",m.evidence_id,"","",""])]));
    folder.file("证据索引.xlsx",await createXlsx("证据索引",[["证据编号","素材编号","机构","平台","发布时间","标题","原始链接","采集时间"],...materials.map(m=>{const c=m.competitors as Record<string,unknown>|null;return[m.evidence_id,m.id,c?.name||m.original_organization,m.platform,m.published_at,m.title,m.source_url,m.collected_at||m.created_at]})]));
    let assetBytes=0;for(const m of materials){const c=m.competitors as Record<string,unknown>|null;for(const asset of (m.material_assets||[]) as Array<Record<string,unknown>>){if(assetBytes>80*1024*1024)break;const downloaded=await sb.storage.from(storageBucket()).download(String(asset.object_path));if(downloaded.data){const bytes=new Uint8Array(await downloaded.data.arrayBuffer());assetBytes+=bytes.byteLength;folder.file(`assets/${cleanName(String(c?.name||m.original_organization||"未知机构"))}/${m.evidence_id}/${cleanName(String(asset.filename||"附件"))}`,bytes)}}}
    const bytes=await zip.generateAsync({type:"uint8array",compression:"DEFLATE"}),objectPath=`external-ai/${job.data.id}/竞对外宣分析包_${stamp}.zip`,upload=await sb.storage.from(storageBucket()).upload(objectPath,bytes,{contentType:"application/zip",upsert:false});if(upload.error)throw upload.error;
    const pkg=await sb.from("external_ai_packages").insert({export_job_id:job.data.id,report_project_id:filters.reportProjectId||null,object_path:objectPath,schema_version:"1.0",material_count:materials.length,status:"completed"}).select().single();if(pkg.error)throw pkg.error;await sb.from("export_jobs").update({status:"completed",object_path:objectPath,item_count:materials.length}).eq("id",job.data.id);
    return Response.json({package:pkg.data,counts,downloadUrl:`/api/files/${encodeURIComponent(objectPath)}`});
  }catch(error){if(exportId)await sb.from("export_jobs").update({status:"failed",error_message:describeSupabaseError(error)}).eq("id",exportId);return Response.json({error:describeSupabaseError(error)},{status:500})}
}
